# Generated by Django 5.1.2 on 2024-10-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('role', models.CharField(choices=[('admin', 'ادمین'), ('instructor', 'مربی'), ('student', 'دانش اموز')], max_length=50, verbose_name='نقش')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
            ],
            options={
                'verbose_name': 'اکانت',
                'verbose_name_plural': 'اکانتهای',
            },
        ),
    ]
